

platform :ios, '13.0'

target 'HMSSDKExample' do
  use_frameworks!
  pod 'HMSSDK', '1.2.1'
  pod 'HMSHLSPlayerSDK', '0.0.2'
  pod 'SwiftyBeaver', '1.9.5'
  pod 'Zip', '2.1.2'
  pod 'Eureka', '5.4.0'
  pod 'SwiftyGif'
end

target 'HMSScreenShare' do
  use_frameworks!
  pod 'HMSBroadcastExtensionSDK', '1.0.0'
end

# Workaround for M1 simulator issue
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Pods-HMSScreenShare'
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"]= "arm64"
      end
    end
  end
end
