

platform :ios, '13.0'

target 'HMSSDKExample' do
  use_frameworks!
  pod 'HMSSDK', '0.9.1'
  pod 'HMSHLSPlayerSDK'
  pod 'Eureka'
  pod 'SwiftyGif'

  target 'HMSSDKExampleTests' do
    inherit! :search_paths
  end
  
end

target 'HMSScreenShare' do
  use_frameworks!
  pod 'HMSBroadcastExtensionSDK'
end

# Workaround for M1 simulator issue
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Pods-HMSScreenShare'
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"]= "arm64"
      end
    end
  end
end
